name: deploy prod
on:
  push:
    branches: [main]

jobs:
  one:
    name: deploy prod action
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOSTIP }}
          username: ${{ secrets.HOSTUSER }}
          key: ${{ secrets.MAINMAC }}
          port: ${{ secrets.HOSTPORT}}
          script: |
            cd ~/notclove.ru/content
            sudo git pull https://github.com/NotClove/nc-content.git
            cd ~/notclove.ru
            sudo hugo -D


